name: Publish Module

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches: 
      - main
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test Module
        run: .\build.ps1 -Task Test -Bootstrap
        shell: pwsh

      - name: Upload Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: tests/out/*.xml

      - name: Publish to PSGallery
        shell: pwsh
        env: 
          PSGALLERY_API_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: ./build.ps1 -Task Publish -Bootstrap
